minSDK change
CaishenNefri/PRz-S4-Projekt-Grzybek pull request #37
Opened 2019-05-12 13:17 UTC by Awuscan

2019-05-12 13:49 UTC, CaishenNefri requested changes
Jest problem z WebView. Zawiesza się podczas próby wpisania czegoś do formularza logowania. 
Nie wyskakuje mi nawet klawiatura.

2019-05-12 14:27 UTC, CaishenNefri commented
Tak wygląda na wirtualce gdy załapie kliknięcie w formularz:
![image](https://user-images.githubusercontent.com/24476768/57583654-c941d600-74d2-11e9-9bd5-7d2de0ca382d.png)

A tak wygląda gdy w ogóle nie chce łapać kliknięcia:
![image](https://user-images.githubusercontent.com/24476768/57583666-e37bb400-74d2-11e9-9a13-fb781a3084a3.png)

2019-05-12 15:42 UTC, CaishenNefri commented
Teraz nie przechodzi dalej niż ten ekran:
![image](https://user-images.githubusercontent.com/24476768/57584578-4f631a00-74dd-11e9-8c40-23dbecb4c28d.png)


https://gist.github.com/CaishenNefri/3bbd4684433874951ffc38d20ee82c36

2019-05-12 15:51 UTC, CaishenNefri approved these changes

2019-05-12 15:52 UTC, CaishenNefri commented
Wszystko BANGLA, przynajmniej u mnie. Przetestujecie

2019-05-13 21:28 UTC, Balowen commented
U mnie nadal włącza się od razu ekran główny z wydarzeniami. Wyłączyłem auto-login w androidzie i nic. Też tak macie?

2019-05-14 10:47 UTC, Balowen approved these changes

2019-05-14 10:48 UTC, mnehrebecki approved these changes

2019-05-14 10:48 UTC, merged